backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog_pages"
    label: "Blog Pages"
    files:
      - file: "blog/index.html"
        label: "Blog - Current"
        name: "blog_index"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }

      - file: "blog/index-new-staic.html"
        label: "Blog - New Static"
        name: "blog_new"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }

      - file: "blog/index-old.html"
        label: "Blog - Old"
        name: "blog_old"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
